[[game_objects]]
id = "wall_dirt_top"
name = "Dirt Wall (Top)"
object_type = "tile"
walkable = false
sprite_sheet = "tiles.png"
[[game_objects.sprites]]
x = 0
y = 0


[[game_objects]]
id = "floor_stone"
name = "Stone Floor"
object_type = "tile"
walkable = true
sprite_sheet = "tiles.png"
[[game_objects.sprites]]
x = 1
y = 6

[[game_objects.sprites]]
x = 2
y = 6

[[game_objects.sprites]]
x = 3
y = 6

[[game_objects.sprites]]
x = 0
y = 6


[[game_objects]]
id = "player"
name = "Player Character"
object_type = "character"
walkable = true
sprite_sheet = "rogues.png"
health = 100
attack = 10
monster = false
defense = 3
healing_power = 0
[[game_objects.sprites]]
x = 0
y = 0


[[game_objects]]
id = "orc"
name = "Orc"
object_type = "character"
walkable = false
health = 40
sprite_sheet = "monsters.png"
monster = true
attack = 5
defense = 5
healing_power = 0
[[game_objects.sprites]]
x = 3
y = 0

[[game_objects.sprites]]
x = 0
y = 0


[[game_objects]]
id = "week_ork"
name = "Orc squire"
object_type = "character"
walkable = false
health = 20
attack = 5
monster = true
sprite_sheet = "monsters.png"
defense = 3
healing_power = 0
[[game_objects.sprites]]
x = 2
y = 0

[[game_objects.sprites]]
x = 5
y = 0

[[game_objects.sprites]]
x = 7
y = 0


[[game_objects]]
id = "stairs"
name = "Stairs Down"
object_type = "goal"
walkable = true
sprite_sheet = "tiles.png"
[[game_objects.sprites]]
x = 7
y = 16


[[game_objects]]
id = "lesser_potion"
name = "Lesser Potion"
object_type = "consumable"
walkable = false
monster = false
healing_power = 20
sprite_sheet = "items.png"
[[game_objects.sprites]]
x = 2
y = 20


